import type { BiomarkerRange } from '@/lib/types';

export const BIOMARKER_RANGES: BiomarkerRange[] = [
  // ─── CBC (hematologic) ────────────────────────────────────────────────────
  {
    name: 'WBC',
    unit: 'K/uL',
    category: 'hematologic',
    standard: { low: 4.5, high: 11.0 },
    functional: { low: 5.0, high: 8.0 },
    notes: 'White blood cell count; elevated may indicate infection or inflammation.',
  },
  {
    name: 'RBC',
    unit: 'M/uL',
    category: 'hematologic',
    standard: { low: 4.5, high: 5.5 },
    functional: { low: 4.7, high: 5.3 },
    notes: 'Red blood cell count; low values suggest anemia.',
  },
  {
    name: 'Hemoglobin',
    unit: 'g/dL',
    category: 'hematologic',
    standard: { low: 13.5, high: 17.5 },
    functional: { low: 14.0, high: 16.0 },
    notes: 'Oxygen-carrying protein in red blood cells.',
  },
  {
    name: 'Hematocrit',
    unit: '%',
    category: 'hematologic',
    standard: { low: 38.3, high: 48.6 },
    functional: { low: 40.0, high: 48.0 },
    notes: 'Percentage of blood volume occupied by red blood cells.',
  },
  {
    name: 'MCV',
    unit: 'fL',
    category: 'hematologic',
    standard: { low: 80, high: 100 },
    functional: { low: 82, high: 92 },
    notes: 'Mean corpuscular volume; low = microcytic, high = macrocytic anemia.',
  },
  {
    name: 'MCH',
    unit: 'pg',
    category: 'hematologic',
    standard: { low: 27, high: 33 },
    functional: { low: 28, high: 32 },
    notes: 'Mean corpuscular hemoglobin; average hemoglobin mass per red cell.',
  },
  {
    name: 'MCHC',
    unit: 'g/dL',
    category: 'hematologic',
    standard: { low: 32, high: 36 },
    functional: { low: 33, high: 35 },
    notes: 'Mean corpuscular hemoglobin concentration.',
  },
  {
    name: 'Platelets',
    unit: 'K/uL',
    category: 'hematologic',
    standard: { low: 150, high: 400 },
    functional: { low: 200, high: 300 },
    notes: 'Platelet count; low increases bleeding risk, high increases clot risk.',
  },

  // ─── CMP (metabolic) ──────────────────────────────────────────────────────
  {
    name: 'Glucose',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 65, high: 99 },
    functional: { low: 75, high: 86 },
    notes: 'Fasting blood glucose; values above functional range suggest early insulin resistance.',
  },
  {
    name: 'BUN',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 7, high: 20 },
    functional: { low: 10, high: 16 },
    notes: 'Blood urea nitrogen; reflects protein catabolism and renal filtration.',
  },
  {
    name: 'Creatinine',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 0.7, high: 1.3 },
    functional: { low: 0.8, high: 1.2 },
    notes: 'Waste product of muscle metabolism; elevated levels indicate impaired kidney function.',
  },
  {
    name: 'eGFR',
    unit: 'mL/min',
    category: 'metabolic',
    standard: { low: 60, high: 120 },
    functional: { low: 90, high: 120 },
    notes: 'Estimated glomerular filtration rate; values >90 indicate optimal kidney function.',
  },
  {
    name: 'Sodium',
    unit: 'mEq/L',
    category: 'metabolic',
    standard: { low: 136, high: 145 },
    functional: { low: 138, high: 142 },
    notes: 'Primary extracellular cation; critical for fluid balance and nerve function.',
  },
  {
    name: 'Potassium',
    unit: 'mEq/L',
    category: 'metabolic',
    standard: { low: 3.5, high: 5.0 },
    functional: { low: 4.0, high: 4.5 },
    notes: 'Primary intracellular cation; critical for cardiac and muscle function.',
  },
  {
    name: 'Chloride',
    unit: 'mEq/L',
    category: 'metabolic',
    standard: { low: 98, high: 106 },
    functional: { low: 100, high: 106 },
    notes: 'Major extracellular anion; important for acid-base and fluid balance.',
  },
  {
    name: 'CO2',
    unit: 'mEq/L',
    category: 'metabolic',
    standard: { low: 23, high: 29 },
    functional: { low: 25, high: 30 },
    notes: 'Bicarbonate; reflects acid-base status. Low may indicate metabolic acidosis.',
  },
  {
    name: 'Calcium',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 8.5, high: 10.5 },
    functional: { low: 9.4, high: 10.0 },
    notes: 'Serum calcium; essential for bone health, muscle contraction, and nerve signaling.',
  },
  {
    name: 'Total Protein',
    unit: 'g/dL',
    category: 'metabolic',
    standard: { low: 6.0, high: 8.3 },
    functional: { low: 6.9, high: 7.4 },
    notes: 'Sum of albumin and globulin; reflects nutritional status and liver synthesis.',
  },
  {
    name: 'Albumin',
    unit: 'g/dL',
    category: 'metabolic',
    standard: { low: 3.5, high: 5.0 },
    functional: { low: 4.0, high: 5.0 },
    notes: 'Most abundant plasma protein; low levels suggest malnutrition or liver disease.',
  },
  {
    name: 'Globulin',
    unit: 'g/dL',
    category: 'metabolic',
    standard: { low: 2.0, high: 3.5 },
    functional: { low: 2.4, high: 2.8 },
    notes: 'Includes immune and transport proteins. Elevated may indicate chronic inflammation.',
  },
  {
    name: 'A/G Ratio',
    unit: 'ratio',
    category: 'metabolic',
    standard: { low: 1.0, high: 2.5 },
    functional: { low: 1.5, high: 2.0 },
    notes: 'Albumin-to-globulin ratio; low ratio may indicate liver disease or immune dysfunction.',
  },
  {
    name: 'Total Bilirubin',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 0.1, high: 1.2 },
    functional: { low: 0.1, high: 0.8 },
    notes: 'Byproduct of red blood cell breakdown. Elevated indicates liver or hemolytic issues.',
  },
  {
    name: 'ALT',
    unit: 'U/L',
    category: 'metabolic',
    standard: { low: 7, high: 56 },
    functional: { low: 10, high: 26 },
    notes: 'Alanine aminotransferase; liver-specific enzyme elevated in hepatocellular damage.',
  },
  {
    name: 'AST',
    unit: 'U/L',
    category: 'metabolic',
    standard: { low: 10, high: 40 },
    functional: { low: 10, high: 26 },
    notes: 'Aspartate aminotransferase; elevated in liver, muscle, or cardiac damage.',
  },
  {
    name: 'ALP',
    unit: 'U/L',
    category: 'metabolic',
    standard: { low: 44, high: 147 },
    functional: { low: 50, high: 100 },
    notes: 'Alkaline phosphatase; elevated in liver, bile duct, or bone disorders.',
  },

  // ─── Lipids (lipid) ───────────────────────────────────────────────────────
  {
    name: 'Total Cholesterol',
    unit: 'mg/dL',
    category: 'lipid',
    standard: { low: 0, high: 200 },
    functional: { low: 150, high: 200 },
    notes: 'Total cholesterol; context-dependent — too low may impair hormone synthesis.',
  },
  {
    name: 'LDL-C',
    unit: 'mg/dL',
    category: 'lipid',
    standard: { low: 0, high: 100 },
    functional: { low: 0, high: 100 },
    notes: 'LDL cholesterol; optimal <70 for high cardiovascular risk individuals.',
  },
  {
    name: 'HDL',
    unit: 'mg/dL',
    category: 'lipid',
    standard: { low: 40, high: 100 },
    functional: { low: 55, high: 100 },
    notes: 'HDL cholesterol; higher values are cardioprotective.',
  },
  {
    name: 'Triglycerides',
    unit: 'mg/dL',
    category: 'lipid',
    standard: { low: 0, high: 150 },
    functional: { low: 0, high: 75 },
    notes: 'Blood fats; elevated levels associated with insulin resistance and cardiovascular risk.',
  },
  {
    name: 'VLDL',
    unit: 'mg/dL',
    category: 'lipid',
    standard: { low: 5, high: 40 },
    functional: { low: 5, high: 20 },
    notes: 'Very low-density lipoprotein; carries triglycerides, precursor to LDL.',
  },

  // ─── Advanced Lipids (lipid_advanced) ────────────────────────────────────
  {
    name: 'LDL-P',
    unit: 'nmol/L',
    category: 'lipid_advanced',
    standard: { low: 0, high: 1300 },
    functional: { low: 0, high: 1000 },
    notes: 'LDL particle number; more predictive of cardiovascular risk than LDL-C alone.',
  },
  {
    name: 'Small LDL-P',
    unit: 'nmol/L',
    category: 'lipid_advanced',
    standard: { low: 0, high: 528 },
    functional: { low: 0, high: 200 },
    notes: 'Small dense LDL particles; most atherogenic LDL subfraction.',
  },
  {
    name: 'LDL Peak Size',
    unit: 'nm',
    category: 'lipid_advanced',
    standard: { low: 20.5, high: 23.0 },
    functional: { low: 21.0, high: 23.0 },
    notes: 'LDL particle size; larger pattern A particles are less atherogenic.',
  },
  {
    name: 'Lp(a)',
    unit: 'nmol/L',
    category: 'lipid_advanced',
    standard: { low: 0, high: 75 },
    functional: { low: 0, high: 30 },
    notes: 'Lipoprotein(a); genetically determined, independent cardiovascular risk factor.',
  },

  // ─── Thyroid (thyroid) ────────────────────────────────────────────────────
  {
    name: 'TSH',
    unit: 'mIU/L',
    category: 'thyroid',
    standard: { low: 0.45, high: 4.5 },
    functional: { low: 1.0, high: 2.0 },
    notes: 'Thyroid-stimulating hormone; most sensitive marker of thyroid function.',
  },
  {
    name: 'Free T3',
    unit: 'pg/mL',
    category: 'thyroid',
    standard: { low: 2.0, high: 4.4 },
    functional: { low: 3.0, high: 4.0 },
    notes: 'Active thyroid hormone; low levels impair metabolism, mood, and energy.',
  },
  {
    name: 'Free T4',
    unit: 'ng/dL',
    category: 'thyroid',
    standard: { low: 0.82, high: 1.77 },
    functional: { low: 1.0, high: 1.5 },
    notes: 'Thyroid prohormone; converted to active T3 in peripheral tissues.',
  },
  {
    name: 'Reverse T3',
    unit: 'ng/dL',
    category: 'thyroid',
    standard: { low: 9.2, high: 24.1 },
    functional: { low: 9.2, high: 18.0 },
    notes: 'Inactive T3 metabolite; elevated in chronic stress and caloric restriction.',
  },
  {
    name: 'TPO Ab',
    unit: 'IU/mL',
    category: 'thyroid',
    standard: { low: 0, high: 34 },
    functional: { low: 0, high: 2 },
    notes: 'Thyroid peroxidase antibodies; elevated indicates autoimmune thyroid disease (Hashimoto\'s).',
  },
  {
    name: 'Tg Ab',
    unit: 'IU/mL',
    category: 'thyroid',
    standard: { low: 0, high: 40 },
    functional: { low: 0, high: 2 },
    notes: 'Thyroglobulin antibodies; elevated in autoimmune thyroid disease.',
  },

  // ─── Hormones (hormonal) ──────────────────────────────────────────────────
  {
    name: 'Total Testosterone',
    unit: 'ng/dL',
    category: 'hormonal',
    standard: { low: 264, high: 916 },
    functional: { low: 600, high: 900 },
    notes: 'Total testosterone; functional range targets upper-normal for optimal vitality.',
  },
  {
    name: 'Free Testosterone',
    unit: 'pg/mL',
    category: 'hormonal',
    standard: { low: 5.0, high: 21.0 },
    functional: { low: 15.0, high: 21.0 },
    notes: 'Unbound bioavailable testosterone; more clinically relevant than total testosterone.',
  },
  {
    name: 'SHBG',
    unit: 'nmol/L',
    category: 'hormonal',
    standard: { low: 10, high: 57 },
    functional: { low: 20, high: 40 },
    notes: 'Sex hormone-binding globulin; high SHBG reduces free testosterone availability.',
  },
  {
    name: 'Estradiol',
    unit: 'pg/mL',
    category: 'hormonal',
    standard: { low: 8, high: 35 },
    functional: { low: 15, high: 30 },
    notes: 'Primary estrogen in men; essential for bone density, libido, and cardiovascular health.',
  },
  {
    name: 'DHEA-S',
    unit: 'ug/dL',
    category: 'hormonal',
    standard: { low: 80, high: 560 },
    functional: { low: 300, high: 500 },
    notes: 'DHEA sulfate; adrenal androgen precursor, declines with age.',
  },
  {
    name: 'Cortisol (AM)',
    unit: 'ug/dL',
    category: 'hormonal',
    standard: { low: 6.2, high: 19.4 },
    functional: { low: 10, high: 15 },
    notes: 'Morning cortisol; should peak 30-60 min after waking. Low may suggest adrenal fatigue.',
  },
  {
    name: 'IGF-1',
    unit: 'ng/mL',
    category: 'hormonal',
    standard: { low: 83, high: 456 },
    functional: { low: 200, high: 350 },
    notes: 'Insulin-like growth factor 1; proxy for growth hormone activity and tissue repair.',
  },
  {
    name: 'Insulin (fasting)',
    unit: 'uIU/mL',
    category: 'hormonal',
    standard: { low: 2.6, high: 24.9 },
    functional: { low: 2.0, high: 5.0 },
    notes: 'Fasting insulin; elevated levels precede glucose dysregulation by years.',
  },
  {
    name: 'Leptin',
    unit: 'ng/mL',
    category: 'hormonal',
    standard: { low: 1.0, high: 11.0 },
    functional: { low: 2.0, high: 6.0 },
    notes: 'Satiety hormone produced by adipose tissue; elevated in leptin resistance.',
  },

  // ─── Inflammatory (inflammatory) ─────────────────────────────────────────
  {
    name: 'CRP',
    unit: 'mg/L',
    category: 'inflammatory',
    standard: { low: 0, high: 10.0 },
    functional: { low: 0, high: 1.0 },
    notes: 'C-reactive protein; non-specific acute-phase inflammatory marker.',
  },
  {
    name: 'hs-CRP',
    unit: 'mg/L',
    category: 'inflammatory',
    standard: { low: 0, high: 3.0 },
    functional: { low: 0, high: 1.0 },
    notes: 'High-sensitivity CRP; values >3 indicate elevated cardiovascular risk.',
  },
  {
    name: 'ESR',
    unit: 'mm/hr',
    category: 'inflammatory',
    standard: { low: 0, high: 22 },
    functional: { low: 0, high: 10 },
    notes: 'Erythrocyte sedimentation rate; non-specific marker of systemic inflammation.',
  },
  {
    name: 'Ferritin',
    unit: 'ng/mL',
    category: 'inflammatory',
    standard: { low: 30, high: 400 },
    functional: { low: 40, high: 150 },
    notes: 'Iron storage protein; also an acute-phase reactant elevated in inflammation.',
  },
  {
    name: 'Homocysteine',
    unit: 'umol/L',
    category: 'inflammatory',
    standard: { low: 5, high: 15 },
    functional: { low: 5, high: 7 },
    notes: 'Amino acid metabolite; elevated levels damage endothelium and increase cardiovascular risk.',
  },
  {
    name: 'Fibrinogen',
    unit: 'mg/dL',
    category: 'inflammatory',
    standard: { low: 200, high: 400 },
    functional: { low: 200, high: 300 },
    notes: 'Clotting protein and acute-phase reactant; elevated levels increase thrombotic risk.',
  },

  // ─── Vitamins/Nutrients (nutritional) ────────────────────────────────────
  {
    name: '25(OH)D',
    unit: 'ng/mL',
    category: 'nutritional',
    standard: { low: 30, high: 100 },
    functional: { low: 50, high: 80 },
    notes: 'Vitamin D (25-hydroxyvitamin D); essential for immune function, bone, and hormone production.',
  },
  {
    name: 'B12',
    unit: 'pg/mL',
    category: 'nutritional',
    standard: { low: 200, high: 1100 },
    functional: { low: 500, high: 1000 },
    notes: 'Vitamin B12; critical for methylation, nerve function, and red blood cell synthesis.',
  },
  {
    name: 'Folate',
    unit: 'ng/mL',
    category: 'nutritional',
    standard: { low: 5.4, high: 25 },
    functional: { low: 10, high: 25 },
    notes: 'Folate (vitamin B9); critical for DNA synthesis and methylation pathways.',
  },
  {
    name: 'Iron',
    unit: 'ug/dL',
    category: 'nutritional',
    standard: { low: 60, high: 170 },
    functional: { low: 80, high: 120 },
    notes: 'Serum iron; low levels contribute to fatigue and impaired oxygen transport.',
  },
  {
    name: 'TIBC',
    unit: 'ug/dL',
    category: 'nutritional',
    standard: { low: 250, high: 370 },
    functional: { low: 275, high: 350 },
    notes: 'Total iron-binding capacity; elevated in iron deficiency, low in iron overload.',
  },
  {
    name: 'Iron Sat%',
    unit: '%',
    category: 'nutritional',
    standard: { low: 15, high: 55 },
    functional: { low: 25, high: 45 },
    notes: 'Transferrin saturation; low indicates iron deficiency, high may indicate hemochromatosis.',
  },

  // ─── Metabolic extras (metabolic) ────────────────────────────────────────
  {
    name: 'HbA1c',
    unit: '%',
    category: 'metabolic',
    standard: { low: 4.0, high: 5.7 },
    functional: { low: 4.0, high: 5.3 },
    notes: 'Glycated hemoglobin; reflects average blood glucose over ~90 days.',
  },
  {
    name: 'Fasting Glucose',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 65, high: 99 },
    functional: { low: 75, high: 86 },
    notes: 'Fasting plasma glucose; values 87-99 are high-normal and may indicate early IR.',
  },
  {
    name: 'Fasting Insulin',
    unit: 'uIU/mL',
    category: 'metabolic',
    standard: { low: 2.6, high: 24.9 },
    functional: { low: 2.0, high: 5.0 },
    notes: 'Fasting insulin; most sensitive early marker of insulin resistance.',
  },
  {
    name: 'HOMA-IR',
    unit: 'index',
    category: 'metabolic',
    standard: { low: 0, high: 2.5 },
    functional: { low: 0, high: 1.5 },
    notes: 'Homeostatic model assessment of insulin resistance; calculated from fasting glucose and insulin.',
  },
  {
    name: 'Uric Acid',
    unit: 'mg/dL',
    category: 'metabolic',
    standard: { low: 3.0, high: 7.0 },
    functional: { low: 3.5, high: 5.5 },
    notes: 'End product of purine metabolism; elevated levels associated with gout and cardiovascular risk.',
  },
  {
    name: 'MMA',
    unit: 'nmol/L',
    category: 'metabolic',
    standard: { low: 0, high: 378 },
    functional: { low: 0, high: 250 },
    notes: 'Methylmalonic acid; functional marker of B12 status, elevated before serum B12 drops.',
  },
];

/**
 * Look up a biomarker reference range by name (case-insensitive).
 */
export function getRange(name: string): BiomarkerRange | undefined {
  const normalized = name.trim().toLowerCase();
  return BIOMARKER_RANGES.find(
    (r) => r.name.toLowerCase() === normalized,
  );
}
